version: '3'

services:
  site:
    container_name: isotopekit_admin_panel
    image: jekyll/jekyll:3.8.6
    command: jekyll serve --livereload --verbose
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle